apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: azure-managed-disk
    namespace: pingpong
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi